### PR TITLE
Make projects usable in Streams Studio

### PR DESCRIPTION
**Pull request by natashadsilva**

### CODE REVIEW

**Comment by ddebrunner** [comment]
@natashadsilva Are there instructions how to create portable Streams Studio project files that don't have dependencies on specific paths?

**Comment by natashadsilva** [comment]
I'm not sure what you mean by "dependencies on specific paths" - Do you mean dependencies on file system paths?

**Comment by ddebrunner** [comment]
Yes - how do I create project files without having hardcoded paths from my local machine?

**Comment by natashadsilva** [comment]
If you look at the project files, they actually do not have any path information related to the filesystem. They are just XML  files that describe its name and nature (the kind of project it is, Java, SPL, e.t.c).

In very simple cases I've just copied the `.project` file from an existing project of type X to another folder. Then I changed the project name within the `.project` file, and the new folder is treated as a project of the same type as the original.  More might be needed for the project to actually work properly in Eclipse/Studio, depending on the kind of project. You'll run into all kinds of weird errors if you are missing something. For SPL  I use Studio to convert the toolkit to an SPL project (and thus generate the .project files and whatever else is needed that I don't know ). It isn't a perfect solution, but if that's what you're trying to do I can share my steps.

**Comment by natashadsilva** [comment]
@ddebrunner  any objections to merging?

**Pull request merged**
